### ISSUE TITLE
SendEmailToExchangeServer: Ä and Ö are not working in emails

### ISSUE THREAD

**Issue by Svenskapojkarna** [CommunityHiQ/Frends.Community.Email#31]
There is an issue with encoding where letters ä and ö are not shown correctly when UTF-8 is used as encoding.

**Comment by HakanJ67** [comment]
It's not just about ä and ö. Other characters are also displayed incorrectly, such as å.

**Comment by Svenskapojkarna** [comment]
Fixed in version 4.0.0. Encoding-parameter has been removed to prevent modification of message content.
